### ISSUE TITLE
Using `sequelize.sync()` is not advised. Sequelize encourage the use of the CLI to run migration or seeders

### ISSUE THREAD

**Issue by coolbeatz71** [willjw3/sequelize-typescript-tutorial#1]
Btw, using `sequelize.sync()` is not advised. Sequelize encourage the use of the CLI to run migration or seeders

**Comment by willjw3** [comment]
@coolbeatz71 I left a response at YouTube. I'm going to close this issue as your comment is more a concern of best practices for developing production apps and the code in this repo is just the source code for a tutorial that has already been published.
Thanks for following the tutorial.
